### ISSUE TITLE
Any interest in adding your plugin to the trac-hacks organization?

### ISSUE THREAD

**Issue by rjollos** [trac-hacks/mantis2trac#3]
Hi,

I'm an administrator for trac-hacks.org.  We've created an organization on GitHub and are inviting authors of trac-hacks plugins to join the organization.  Your repository could be transferred into the organization as described in the [GitHub docs](https://help.github.com/articles/transferring-a-repository/).  You'd retain full control over the repository, but the hope is that it will be easier for users on GitHub to find trac-hacks plugins, such as yours, by viewing the trac-hacks organization. We also plan to eventually add search capabilities that aggregate the plugins available on trac-hacks.org and github.com/trac-hacks, to provide a single index of all plugins available for Trac.

In the future, if you choose to no longer maintain the plugin, the organization would be able to provide commit access to new developers.  This would only be done with your permission, as has been the policy for plugins hosted on trac-hacks.org.  If you've already decided to no longer maintain the plugin, we would particularly appreciate you transferring the plugin to the trac-hacks organization so that we can help find new maintainers for it.

Thank you for your consideration.

Kind regards,
Ryan

**Comment by Aeon** [comment]
Sure, I'd be happy to transfer it. I'm not really maintaining it other than merging an occasional fork. I tried transferring, but it says I cannot create repositories in trac-hacks org - perhaps you need to do something before I can do it?

**Comment by rjollos** [comment]
Thanks! You should have just received an invite to join the trac-hacks organization. You can execute [these steps](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-a-repository-to-another-user-account-or-to-an-organization) and transfer the repository. After you transfer the repository I'll set you as the Admin for your repository.

**Comment by Aeon** [comment]
Transferred!

**Comment by rjollos** [comment]
Thanks!

**Comment by Aeon** [comment]
We could import the issues from trac repo to the github repo with https://github.com/slinkp/trac2issues ?

**Comment by rjollos** [comment]
I've never used it so I can't say. The newest of the issues on trac-hacks.org is 10 years old, so I'd take the position that anyone encountering an issue could open a new ticket. But if you are determined to fix them I guess it could be useful to import the 6 issues.

**Comment by Aeon** [comment]
Wrote a quick script and migrated them over. I doubt I'll have time to review/fix them, but it's useful for project history, and so people are aware of known issues.

**Comment by Aeon** [comment]
@rjollos - if you are interested in doing this for other projects, here's the tool with my modifications: https://github.com/Aeon/trac2github

**Comment by rjollos** [comment]
Thanks.
